import { createContext, useContext, useEffect, useState } from "react";

const STORAGE_KEY = "romanestate-language";

const baseTranslations = {
  en: {
    nav: {
      home: "Home",
      listings: "Listings",
      nearby: "Nearby",
      favorites: "Favorites",
      deals: "Deals",
      profile: "Profile",
      signIn: "Sign in",
      signUp: "Sign up",
      language: "Language",
    },
    home: {
      title: "Find homes that fit your lifestyle",
      description:
        "Search city by city, compare budgets, explore nearby places and keep every conversation with your realtor in one calm workflow.",
      searchBadge: "Live marketplace search",
      trustOne: "Verified listings",
      trustTwo: "Fast realtor replies",
      trustThree: "Secure deal flow",
      popularCities: "Popular cities",
      statsYears: "Years of experience",
      statsAwards: "Awards gained",
      statsReady: "Homes ready",
    },
    search: {
      buy: "Buy",
      rent: "Rent",
      city: "City",
      allCities: "All cities",
      minPrice: "Min price",
      maxPrice: "Max price",
      property: "Property",
      bedrooms: "Bedrooms",
      button: "Search",
      quickLabel: "Popular searches",
      reset: "Reset",
    },
    filter: {
      resultsFor: "Search results for {city}",
      resultsDefault: "Search results",
      location: "Location",
      type: "Type",
      property: "Property",
      minPrice: "Min price",
      maxPrice: "Max price",
      bedroom: "Bedrooms",
      sortBy: "Sort by",
      apply: "Apply filters",
      any: "Any",
      newest: "Newest first",
      priceHigh: "Highest price",
      priceLow: "Lowest price",
      bedroomHigh: "Most bedrooms",
      cityAz: "City A-Z",
      quickFilters: "Quick filters",
      quickFiltersDescription: "Save your best searches and jump between value, family and verified picks in one click.",
      highlightAll: "All listings",
      highlightVerified: "Verified",
      highlightBestValue: "Best value",
      highlightFamily: "Family ready",
      highlightPremium: "Premium homes",
      saveSearch: "Save search",
      reset: "Reset",
      savedSearches: "Saved searches",
      savedSearchesDescription: "Keep your favorite combinations close and reopen them from any device session.",
      openSavedSearch: "Open search",
      deleteSavedSearch: "Delete saved search",
      savedFallback: "Current market search",
      savedBedrooms: "{count}+ beds",
    },
    listPage: {
      collection: "RomanEstate collection",
      resultsTitleDefault: "Curated property feed",
      resultsTitleCity: "Homes in {city}",
      heroDescription:
        "Explore a cleaner marketplace flow with live sorting, city-specific filters and quick access to listings worth saving or opening as a deal.",
      listingsFound: "Listings found",
      averagePrice: "Average price",
      averageArea: "Average size",
      shortlistCount: "Shortlist picks",
      sortingMode: "Sorting mode",
      highlightMode: "Highlight mode",
      featuredNow: "Featured now",
      featuredTitle: "Hand-picked ribbon",
      compareEyebrow: "Compare mode",
      compareTitle: "Shortlist comparison",
      compareDescription: "Compare the homes you saved side by side before opening a deal request.",
      clearCompare: "Clear compare",
      removeCompare: "Remove from compare",
      recentlyViewedEyebrow: "Recently viewed",
      recentlyViewedTitle: "Pick up where you left off",
      recentTrackedCount: "Tracked visits",
      recentPriceDropsCount: "Recent price drops",
      recentSavings: "Savings in view",
      allResults: "All results",
      browseFeed: "Browse the feed",
      loadMore: "Load more listings",
      emptyTitle: "Nothing matches this search",
      emptyDescription: "Adjust the filters, try another city or remove the price limits.",
      loading: "Loading...",
      loadingError: "Error loading posts.",
    },
    auth: {
      loginTitle: "Welcome back",
      loginSubtitle: "Continue your property journey, shortlist homes and reopen the chat with your realtor.",
      username: "Username",
      password: "Password",
      login: "Login",
      loginSwitch: "Don't have an account?",
      loginSwitchCta: "Create one",
      registerTitle: "Create an account",
      registerSubtitle: "Save favorites, track deals and keep your conversations in one account.",
      email: "Email",
      phone: "Phone number",
      register: "Register",
      registerSwitch: "Already have an account?",
      registerSwitchCta: "Sign in",
      heroLabel: "Client access",
    },
    footer: {
      description:
        "Digital marketplace for property discovery, deal requests and direct realtor support. Built for fast search, clean deal flow and secure role-based operations.",
      marketplace: "Marketplace",
      browseListings: "Browse listings",
      nearbyProperties: "Nearby properties",
      account: "Account",
      rights: "All rights reserved.",
    },
    support: {
      title: "RomanEstate chat",
      subtitle: "Ask a realtor anything about a property",
      close: "Close",
      guestTitle: "Sign in to chat with a realtor",
      guestDescription: "Save listings, ask questions and continue the conversation later.",
      openLogin: "Open login",
      loading: "Loading conversation...",
      empty: "Start the conversation and your realtor will see it in the queue.",
      placeholder: "Write your question for the realtor...",
      send: "Send",
      sending: "Sending...",
      launcherOpen: "Hide",
      launcherClosed: "Ask",
    },
    gallery: {
      label: "Photo gallery",
      emptyTitle: "Gallery coming soon",
      emptyDescription: "This listing does not have a photo gallery yet, but the page is ready for facade, interior, and floor plan shots.",
      sequenceLabel: "Gallery flow",
      sequenceTitle: "Room-by-room sequence",
      sequenceDescription: "Jump between facade, interior, and floor plan shots in the order buyers usually review them.",
      openFullscreen: "Open fullscreen",
      fullscreenLabel: "Immersive mode",
      close: "Close gallery",
      previous: "Previous photo",
      next: "Next photo",
      counter: "Photo {current} of {total}",
      photoLabel: "Photo {count}",
    },
    card: {
      forRent: "For rent",
      forSale: "For sale",
      cityFallback: "City",
      deletePost: "Delete post",
      editPost: "Edit post",
      bedroom: "{count} bedroom",
      bathroom: "{count} bathroom",
      contact: "Contact: {value}",
      contactMissing: "Not provided",
      contactLogin: "Login to contact",
      verifiedOwner: "Verified owner",
      viewDetails: "View details",
      monthlyEstimate: "Est. monthly",
      pricePerSqft: "Price / sqft",
      size: "Size",
      compare: "Compare",
      compared: "Compared",
      badgeVerified: "Verified",
      badgeBestValue: "Best value",
      badgeFamily: "Family ready",
      badgePremium: "Premium",
      badgePriceDrop: "Price drop",
      priceAlertOn: "Price watch on",
      priceAlertOff: "Price watch off",
      priceDropDetected: "Down {amount} since you saved it",
      savedPriceReference: "Saved when it was {value}",
      turnOnAlert: "Turn on alert",
      turnOffAlert: "Mute alert",
      recentViewStatus: "Recent visit",
      recentViewPriceDrop: "Down {amount} since your last visit",
      recentViewPriceReference: "Last viewed at {value}",
      recentViewHint: "Reopen the listing to refresh the watch.",
    },
    nearby: {
      noData: "No nearby places data available.",
      empty: "No nearby places found.",
    },
    single: {
      exploreNearby: "Explore nearby",
      owner: "Owner",
      unknownUser: "Unknown user",
      general: "General",
      utilities: "Utilities",
      utilitiesOwner: "Owner is responsible",
      utilitiesTenant: "Tenant is responsible",
      utilitiesShared: "Shared",
      petPolicy: "Pet policy",
      petAllowed: "Pets allowed",
      petNotAllowed: "Pets not allowed",
      incomePolicy: "Income policy",
      sizes: "Sizes",
      beds: "{count} beds",
      bathrooms: "{count} bathrooms",
      nearbyPlaces: "Nearby places",
      school: "School",
      busStop: "Bus stop",
      restaurant: "Restaurant",
      away: "{distance} km away",
      location: "Location",
      save: "Save the place",
      saved: "Place saved",
      contact: "Contact: {value}",
      notProvided: "Not provided",
      estMonthly: "Est. monthly",
      estMonthlyHint: "20% down payment, 20-year mortgage model",
      downPayment: "Down payment",
      downPaymentHint: "Typical starting point before mortgage approval",
      marketPosition: "Market position",
      marketPositionHint: "Compared with similar homes in {city}",
      marketValueGood: "Below local median",
      marketValueBalanced: "In line with the market",
      marketValuePremium: "Above local median",
      factsTitle: "Quick facts",
      factCity: "City",
      factType: "Listing type",
      factProperty: "Property",
      factArea: "Area",
      factPricePerSqft: "Price / sqft",
      factBedrooms: "Bedrooms",
      factBathrooms: "Bathrooms",
      factOwner: "Owner",
      similarEyebrow: "More like this",
      similarTitle: "Similar homes nearby",
      dealFlow: "Deal flow",
      openDeal: "Open a deal request",
      dealHint: "Your assigned realtor will see it in the pipeline",
      dealPlaceholder:
        "Tell the realtor what matters to you: budget, timeline, mortgage needs, visit request...",
      dealOpening: "Opening deal...",
      dealButton: "Start deal request",
    },
    profile: {
      eyebrow: "Client dashboard",
      phoneMissing: "Phone not provided yet",
      updateProfile: "Update profile",
      logout: "Logout",
      listings: "Listings",
      favorites: "Favorites",
      activeDeals: "Active deals",
      inventoryEyebrow: "Your inventory",
      inventoryTitle: "My listings",
      createPost: "Create new post",
      emptyListingsTitle: "You have not published a listing yet",
      emptyListingsDescription: "Create your first property card and it will appear here.",
      savedEyebrow: "Saved board",
      savedTitle: "Favorite properties",
      emptySavedTitle: "No favorites saved yet",
      emptySavedDescription: "Browse the feed, save homes you like and build your shortlist here.",
      savedAlertsEyebrow: "Price watch",
      savedAlertsTitle: "Saved listing alerts",
      savedAlertsDescription: "Keep an eye on the homes you saved and react faster when the asking price drops.",
      alertsEnabledCount: "Alerts enabled",
      priceDropsCount: "Live price drops",
      savingsOpportunity: "Potential savings",
      alertToggleError: "Failed to update the price alert. Please try again.",
      dealsEyebrow: "Negotiation hub",
      dealsTitle: "Deal Requests",
      loadError: "Failed to load profile.",
    },
    profileUpdate: {
      title: "Update profile",
      username: "Username",
      email: "Email",
      password: "Password",
      phone: "Phone number",
      avatar: "Avatar URL",
      avatarPlaceholder: "https://example.com/avatar.jpg",
      submit: "Update",
      error: "Profile update failed",
    },
    deals: {
      justNow: "Just now",
      emptyTitle: "No active deal requests yet",
      emptyDescription:
        "Open a listing you love, start a deal request and your assigned realtor will pick it up here.",
      untitled: "Untitled property",
      cityPending: "City pending",
      rentDeal: "Rent deal",
      buyDeal: "Purchase deal",
      declined: "Request declined by staff review",
      assignedRealtor: "Assigned realtor",
      autoAssign: "Will be assigned automatically",
      updated: "Updated",
      yourNote: "Your note",
    },
    forms: {
      addPost: "Add new post",
      editPost: "Edit post",
      title: "Title",
      price: "Price",
      address: "Address",
      description: "Description",
      city: "City",
      bedrooms: "Bedroom number",
      bathrooms: "Bathroom number",
      latitude: "Latitude",
      longitude: "Longitude",
      type: "Type",
      property: "Property",
      utilities: "Utilities policy",
      utilitiesOwner: "Owner is responsible",
      utilitiesTenant: "Tenant is responsible",
      utilitiesShared: "Shared",
      petPolicy: "Pet policy",
      petsAllowed: "Allowed",
      petsNotAllowed: "Not allowed",
      incomePolicy: "Income policy",
      incomePlaceholder: "Income policy",
      size: "Total size (sqft)",
      school: "School",
      bus: "Bus",
      restaurant: "Restaurant",
      addPhotos: "Add photos",
      photoRequirementsTitle: "Listing photo requirements",
      photoRequirementsDescription:
        "To publish a property, add at least one exterior/facade image, one interior image, and one floor plan. You can upload multiple photos in every category and they will stay attached to the listing.",
      photoCoverageHint: "Required before publish",
      photoExteriorTitle: "Exterior / facade",
      photoExteriorDescription: "Street view, facade, entry group, courtyard, or building exterior.",
      photoInteriorTitle: "Interior",
      photoInteriorDescription: "Living spaces, kitchen, bedrooms, bathrooms, and finishes.",
      photoFloorPlanTitle: "Floor plan",
      photoFloorPlanDescription: "Layout image, floor plan, or room scheme for the property.",
      addExteriorPhotos: "Add exterior photos",
      addInteriorPhotos: "Add interior photos",
      addFloorPlanPhotos: "Add floor plan images",
      photoCategoryMissing: "Add the missing required photo categories",
      photoCategoryLabel: "Photo category",
      photoCategoryExterior: "Exterior / facade",
      photoCategoryInterior: "Interior",
      photoCategoryFloorPlan: "Floor plan",
      photoCount: "{count} uploaded",
      photoEmptyState: "No photos added in this category yet.",
      remove: "Remove",
      saving: "Saving...",
      add: "Add",
      update: "Update",
      createError: "Failed to create listing",
      updateError: "Failed to update listing",
      loadError: "Failed to load post",
      missingPost: "Post not found",
      loading: "Loading...",
    },
    catalog: {
      anyBedrooms: "Any",
      property: {
        apartment: "Apartment",
        house: "House",
        condo: "Condo",
        land: "Land",
      },
      listingType: {
        buy: "Buy",
        rent: "Rent",
      },
      bedrooms: {
        one: "1+",
        two: "2+",
        three: "3+",
        four: "4+",
        fivePlus: "5+",
      },
    },
  },
  ru: {
    nav: {
      home: "Главная",
      listings: "Объекты",
      nearby: "Рядом",
      favorites: "Избранное",
      deals: "Сделки",
      profile: "Профиль",
      signIn: "Войти",
      signUp: "Регистрация",
      language: "Язык",
    },
    home: {
      title: "Найдите дом под свой ритм жизни",
      description:
        "Ищите по городам, сравнивайте бюджеты, смотрите объекты рядом и держите весь диалог с риелтором в одном аккуратном сценарии.",
      searchBadge: "Живой поиск по маркетплейсу",
      trustOne: "Проверенные объявления",
      trustTwo: "Быстрые ответы риелтора",
      trustThree: "Безопасный процесс сделки",
      popularCities: "Популярные города",
      statsYears: "Лет опыта",
      statsAwards: "Наград",
      statsReady: "Готовых объектов",
    },
    search: {
      buy: "Купить",
      rent: "Аренда",
      city: "Город",
      allCities: "Все города",
      minPrice: "Цена от",
      maxPrice: "Цена до",
      property: "Тип объекта",
      bedrooms: "Спальни",
      button: "Найти",
      quickLabel: "Быстрые направления",
      reset: "Сбросить",
    },
    filter: {
      resultsFor: "Результаты поиска: {city}",
      resultsDefault: "Результаты поиска",
      location: "Локация",
      type: "Формат",
      property: "Объект",
      minPrice: "Цена от",
      maxPrice: "Цена до",
      bedroom: "Спальни",
      sortBy: "Сортировка",
      apply: "Применить фильтры",
      any: "Любой",
      newest: "Сначала новые",
      priceHigh: "Сначала дорогие",
      priceLow: "Сначала дешевые",
      bedroomHigh: "Больше спален",
      cityAz: "Город А-Я",
      quickFilters: "Быстрые фильтры",
      quickFiltersDescription: "Сохраняйте удачные подборки и переключайтесь между выгодными, семейными и проверенными вариантами в один клик.",
      highlightAll: "Все объекты",
      highlightVerified: "Проверенные",
      highlightBestValue: "Выгодные",
      highlightFamily: "Для семьи",
      highlightPremium: "Премиум",
      saveSearch: "Сохранить поиск",
      savedSearches: "Сохранённые поиски",
      savedSearchesDescription: "Держите любимые комбинации фильтров под рукой и открывайте их в любой следующей сессии.",
      openSavedSearch: "Открыть поиск",
      deleteSavedSearch: "Удалить поиск",
      savedFallback: "Текущий поиск по рынку",
      savedBedrooms: "От {count} спален",
    },
    listPage: {
      collection: "Подборка RomanEstate",
      resultsTitleDefault: "Кураторская лента объектов",
      resultsTitleCity: "Объекты в {city}",
      heroDescription:
        "Более чистый сценарий поиска: живая сортировка, фильтры по городам и быстрый доступ к объектам, которые стоит сохранить или перевести в сделку.",
      listingsFound: "Найдено объектов",
      averagePrice: "Средняя цена",
      averageArea: "Средняя площадь",
      shortlistCount: "В shortlist",
      sortingMode: "Режим сортировки",
      highlightMode: "Режим акцентов",
      featuredNow: "Сейчас в фокусе",
      featuredTitle: "Ручная подборка",
      compareEyebrow: "Режим сравнения",
      compareTitle: "Сравнение shortlist",
      compareDescription: "Сопоставляйте сохранённые объекты бок о бок, прежде чем открывать сделку.",
      clearCompare: "Очистить сравнение",
      removeCompare: "Убрать из сравнения",
      recentlyViewedEyebrow: "Недавно смотрели",
      recentlyViewedTitle: "Продолжайте с того места, где остановились",
      recentTrackedCount: "Отслеживаемые просмотры",
      recentPriceDropsCount: "Снижения цены",
      recentSavings: "Потенциал экономии",
      allResults: "Все результаты",
      browseFeed: "Просмотр ленты",
      loadMore: "Показать еще",
      emptyTitle: "По этому запросу ничего не найдено",
      emptyDescription: "Измените фильтры, попробуйте другой город или уберите ценовые ограничения.",
      loading: "Загрузка...",
      loadingError: "Не удалось загрузить объекты.",
    },
    auth: {
      loginTitle: "С возвращением",
      loginSubtitle: "Продолжайте поиск, сохраняйте объекты и возвращайтесь к диалогу с риелтором в пару кликов.",
      username: "Имя пользователя",
      password: "Пароль",
      login: "Войти",
      loginSwitch: "Еще нет аккаунта?",
      loginSwitchCta: "Создать",
      registerTitle: "Создайте аккаунт",
      registerSubtitle: "Сохраняйте избранное, отслеживайте сделки и держите всю коммуникацию в одном профиле.",
      email: "Email",
      phone: "Телефон",
      register: "Зарегистрироваться",
      registerSwitch: "Уже есть аккаунт?",
      registerSwitchCta: "Войти",
      heroLabel: "Клиентский вход",
    },
    footer: {
      description:
        "Цифровой маркетплейс для поиска недвижимости, заявок на сделки и прямой связи с риелтором. Быстрый поиск, чистый flow сделки и безопасная role-based логика.",
      marketplace: "Маркетплейс",
      browseListings: "Смотреть объекты",
      nearbyProperties: "Объекты рядом",
      account: "Аккаунт",
      rights: "Все права защищены.",
    },
    support: {
      title: "Чат RomanEstate",
      subtitle: "Спросите риелтора об объекте",
      close: "Закрыть",
      guestTitle: "Войдите, чтобы написать риелтору",
      guestDescription: "Сохраняйте объекты, задавайте вопросы и продолжайте диалог позже.",
      openLogin: "Открыть вход",
      loading: "Загружаем переписку...",
      empty: "Начните диалог, и риелтор увидит его в своей очереди.",
      placeholder: "Напишите вопрос риелтору...",
      send: "Отправить",
      sending: "Отправка...",
      launcherOpen: "Скрыть",
      launcherClosed: "Чат",
    },
    gallery: {
      label: "Фотогалерея",
      emptyTitle: "Галерея скоро появится",
      emptyDescription: "У этого объекта пока нет полной фотогалереи, но страница уже готова для фасада, интерьера и планировки.",
      sequenceLabel: "Сценарий просмотра",
      sequenceTitle: "Последовательность по комнатам",
      sequenceDescription: "Переключайтесь между фасадом, интерьером и планировкой в том порядке, в котором покупатели обычно изучают объект.",
      openFullscreen: "Открыть на весь экран",
      fullscreenLabel: "Полноэкранный режим",
      close: "Закрыть галерею",
      previous: "Предыдущее фото",
      next: "Следующее фото",
      counter: "Фото {current} из {total}",
      photoLabel: "Фото {count}",
    },
    card: {
      forRent: "В аренду",
      forSale: "На продажу",
      cityFallback: "Город",
      deletePost: "Удалить объект",
      editPost: "Редактировать объект",
      bedroom: "{count} спальня",
      bathroom: "{count} ванная",
      contact: "Контакт: {value}",
      contactMissing: "Не указан",
      contactLogin: "Войдите, чтобы связаться",
      verifiedOwner: "Проверенный владелец",
      viewDetails: "Подробнее",
      monthlyEstimate: "Платёж в месяц",
      pricePerSqft: "Цена / sqft",
      size: "Площадь",
      compare: "Сравнить",
      compared: "В сравнении",
      badgeVerified: "Проверено",
      badgeBestValue: "Выгодно",
      badgeFamily: "Для семьи",
      badgePremium: "Премиум",
      badgePriceDrop: "Цена снижена",
      priceAlertOn: "Отслеживание цены включено",
      priceAlertOff: "Отслеживание цены выключено",
      priceDropDetected: "Цена снизилась на {amount} с момента сохранения",
      savedPriceReference: "Вы сохранили объект по цене {value}",
      turnOnAlert: "Включить уведомление",
      turnOffAlert: "Отключить уведомление",
      recentViewStatus: "Недавний просмотр",
      recentViewPriceDrop: "Цена снизилась на {amount} с последнего визита",
      recentViewPriceReference: "В прошлый раз вы видели цену {value}",
      recentViewHint: "Откройте объект ещё раз, чтобы обновить отслеживание.",
    },
    nearby: {
      noData: "Нет данных по объектам рядом.",
      empty: "Рядом ничего не найдено.",
    },
    single: {
      exploreNearby: "Смотреть рядом",
      owner: "Владелец",
      unknownUser: "Неизвестный пользователь",
      general: "Общее",
      utilities: "Коммунальные услуги",
      utilitiesOwner: "Оплачивает собственник",
      utilitiesTenant: "Оплачивает арендатор",
      utilitiesShared: "Совместно",
      petPolicy: "Политика по питомцам",
      petAllowed: "Питомцы разрешены",
      petNotAllowed: "Питомцы запрещены",
      incomePolicy: "Требования к доходу",
      sizes: "Параметры",
      beds: "{count} спальных мест",
      bathrooms: "{count} ванных",
      nearbyPlaces: "Что рядом",
      school: "Школа",
      busStop: "Остановка",
      restaurant: "Ресторан",
      away: "{distance} км",
      location: "Расположение",
      save: "Сохранить объект",
      saved: "Объект сохранен",
      contact: "Контакт: {value}",
      notProvided: "Не указан",
      estMonthly: "Платёж в месяц",
      estMonthlyHint: "Модель: 20% первоначальный взнос и ипотека на 20 лет",
      downPayment: "Первоначальный взнос",
      downPaymentHint: "Типовая отправная точка перед одобрением ипотеки",
      marketPosition: "Позиция на рынке",
      marketPositionHint: "По сравнению с похожими объектами в городе {city}",
      marketValueGood: "Ниже медианы по рынку",
      marketValueBalanced: "На уровне рынка",
      marketValuePremium: "Выше медианы по рынку",
      factsTitle: "Ключевые факты",
      factCity: "Город",
      factType: "Формат объявления",
      factProperty: "Тип объекта",
      factArea: "Площадь",
      factPricePerSqft: "Цена / sqft",
      factBedrooms: "Спальни",
      factBathrooms: "Ванные",
      factOwner: "Владелец",
      similarEyebrow: "Похожие варианты",
      similarTitle: "Похожие объекты рядом",
      dealFlow: "Сценарий сделки",
      openDeal: "Открыть заявку на сделку",
      dealHint: "Назначенный риелтор увидит ее в своей воронке",
      dealPlaceholder:
        "Напишите, что для вас важно: бюджет, сроки, ипотека, просьба о показе и другие детали...",
      dealOpening: "Открываем заявку...",
      dealButton: "Начать сделку",
    },
    profile: {
      eyebrow: "Клиентский кабинет",
      phoneMissing: "Телефон пока не указан",
      updateProfile: "Обновить профиль",
      logout: "Выйти",
      listings: "Объекты",
      favorites: "Избранное",
      activeDeals: "Активные сделки",
      inventoryEyebrow: "Ваши публикации",
      inventoryTitle: "Мои объекты",
      createPost: "Создать объект",
      emptyListingsTitle: "Вы еще не опубликовали ни одного объекта",
      emptyListingsDescription: "Создайте первую карточку, и она появится здесь.",
      savedEyebrow: "Сохраненная подборка",
      savedTitle: "Избранные объекты",
      emptySavedTitle: "Избранное пока пустое",
      emptySavedDescription: "Сохраняйте понравившиеся объекты и собирайте свой shortlist здесь.",
      savedAlertsEyebrow: "Контроль цены",
      savedAlertsTitle: "Оповещения по сохранённым объектам",
      savedAlertsDescription: "Следите за сохранёнными объектами и быстрее реагируйте, когда цена продавца снижается.",
      alertsEnabledCount: "Активные уведомления",
      priceDropsCount: "Текущие снижения цены",
      savingsOpportunity: "Потенциальная экономия",
      alertToggleError: "Не удалось обновить уведомление о цене. Попробуйте ещё раз.",
      dealsEyebrow: "Центр переговоров",
      dealsTitle: "Заявки на сделки",
      loadError: "Не удалось загрузить профиль.",
    },
    profileUpdate: {
      title: "Обновить профиль",
      username: "Имя пользователя",
      email: "Email",
      password: "Пароль",
      phone: "Телефон",
      avatar: "Ссылка на аватар",
      avatarPlaceholder: "https://example.com/avatar.jpg",
      submit: "Обновить",
      error: "Не удалось обновить профиль",
    },
    deals: {
      justNow: "Только что",
      emptyTitle: "Активных заявок на сделку пока нет",
      emptyDescription: "Откройте понравившийся объект, начните сделку и назначенный риелтор подхватит ее здесь.",
      untitled: "Объект без названия",
      cityPending: "Город уточняется",
      rentDeal: "Сделка по аренде",
      buyDeal: "Сделка по покупке",
      declined: "Заявка отклонена на этапе проверки",
      assignedRealtor: "Назначенный риелтор",
      autoAssign: "Назначится автоматически",
      updated: "Обновлено",
      yourNote: "Ваша заметка",
    },
    forms: {
      addPost: "Добавить объект",
      editPost: "Редактировать объект",
      title: "Заголовок",
      price: "Цена",
      address: "Адрес",
      description: "Описание",
      city: "Город",
      bedrooms: "Количество спален",
      bathrooms: "Количество ванных",
      latitude: "Широта",
      longitude: "Долгота",
      type: "Формат",
      property: "Тип объекта",
      utilities: "Кто платит за коммунальные",
      utilitiesOwner: "Собственник",
      utilitiesTenant: "Арендатор",
      utilitiesShared: "Совместно",
      petPolicy: "Питомцы",
      petsAllowed: "Разрешены",
      petsNotAllowed: "Запрещены",
      incomePolicy: "Требования к доходу",
      incomePlaceholder: "Укажите требования к доходу",
      size: "Площадь (sqft)",
      school: "Школа",
      bus: "Транспорт",
      restaurant: "Ресторан",
      addPhotos: "Добавить фото",
      photoRequirementsTitle: "Требования к фотографиям",
      photoRequirementsDescription:
        "Чтобы опубликовать объект, добавьте минимум одно фото фасада, одно фото интерьера и одну планировку. В каждую категорию можно загрузить несколько изображений, и они сохраняются вместе с объектом.",
      photoCoverageHint: "Нужно для публикации",
      photoExteriorTitle: "Фасад / экстерьер",
      photoExteriorDescription: "Улица, фасад, входная группа, двор или внешний вид здания.",
      photoInteriorTitle: "Интерьер",
      photoInteriorDescription: "Комнаты, кухня, спальни, санузлы и отделка.",
      photoFloorPlanTitle: "Планировка",
      photoFloorPlanDescription: "План этажа, схема комнат или изображение планировки объекта.",
      addExteriorPhotos: "Добавить фото фасада",
      addInteriorPhotos: "Добавить фото интерьера",
      addFloorPlanPhotos: "Добавить планировки",
      photoCategoryMissing: "Добавьте недостающие обязательные категории фото",
      photoCategoryLabel: "Категория фото",
      photoCategoryExterior: "Фасад / экстерьер",
      photoCategoryInterior: "Интерьер",
      photoCategoryFloorPlan: "Планировка",
      photoCount: "Загружено: {count}",
      photoEmptyState: "В этой категории пока нет фото.",
      remove: "Удалить",
      saving: "Сохраняем...",
      add: "Добавить",
      update: "Обновить",
      createError: "Не удалось создать объект",
      updateError: "Не удалось обновить объект",
      loadError: "Не удалось загрузить объект",
      missingPost: "Объект не найден",
      loading: "Загрузка...",
    },
    catalog: {
      anyBedrooms: "Любое",
      property: {
        apartment: "Квартира",
        house: "Дом",
        condo: "Кондо",
        land: "Участок",
      },
      listingType: {
        buy: "Купить",
        rent: "Аренда",
      },
      bedrooms: {
        one: "1+",
        two: "2+",
        three: "3+",
        four: "4+",
        fivePlus: "5+",
      },
    },
  },
};


function mergeDictionaries(base, extension) {
  if (!extension || typeof extension !== "object") {
    return base;
  }

  const result = { ...base };

  Object.entries(extension).forEach(([key, value]) => {
    if (
      value &&
      typeof value === "object" &&
      !Array.isArray(value) &&
      result[key] &&
      typeof result[key] === "object" &&
      !Array.isArray(result[key])
    ) {
      result[key] = mergeDictionaries(result[key], value);
      return;
    }

    result[key] = value;
  });

  return result;
}

const translationExtensions = {
  en: {
    nav: {
      newBuilds: "New builds",
    },
    home: {
      newBuildHub: "Browse new-build hub",
      digestEyebrow: "Saved search digest",
      digestTitle: "Quick follow-up on your saved searches",
      digestMatches: "{count} active matches",
      digestEmptyTitle: "Save your first search",
      digestEmptyDescription: "Once you save a filter set, we will keep a quick digest for you here.",
      recommendationEyebrow: "Recommended next",
      recommendationTitle: "Listings worth a second look",
      financeEyebrow: "Finance partners",
      financeTitle: "Mortgage programs to compare early",
    },
    support: {
      loadError: "Failed to load chat.",
      sendError: "Failed to send message.",
      openAria: "Open support chat",
      closeAria: "Close support chat",
    },
    filter: {
      advancedTitle: "Advanced discovery",
      advancedDescription: "Layer district, transit, building profile, renovation and price signals on top of the core search.",
      district: "District",
      transit: "Transit",
      buildingType: "Building type",
      renovation: "Renovation",
      newBuild: "New build",
      newBuildOnly: "New-build only",
      priceSignal: "Price signal",
      priceSignalDrop: "Price reduced",
    },
    map: {
      searchAreaTitle: "Map-first search",
      searchAreaHint: "Draw an area, set a radius and focus the feed on that part of the city.",
      drawArea: "Draw area",
      drawingOn: "Drawing on",
      radiusValue: "{value} km",
      searchThisArea: "Search this area",
      resetArea: "Reset area",
      activeAreaNotice: "Map area filter active: {value} km radius.",
    },
    assistant: {
      label: "Helper search",
      title: "Describe what you want in plain language",
      description: "This is a guided helper system / facade AI: it turns your request into filters without depending on a live LLM.",
      placeholder: "Example: new build apartment near metro in Mumbai under 15000000",
      submit: "Build search",
      exampleFamily: "Family-ready 3 bed in Pune under 18000000",
      exampleMetro: "Apartment near metro in Delhi for rent",
      exampleNewBuild: "New-build condo in Mumbai with price drop",
    },
    quiz: {
      launch: "Start housing quiz",
      label: "Onboarding quiz",
      title: "Tell us the shape of your search",
      description: "A short guided quiz to open the right filter set faster.",
      close: "Close",
      city: "City",
      cityPlaceholder: "Mumbai",
      budget: "Budget",
      type: "Goal",
      property: "Property type",
      finance: "Finance path",
      mortgage: "Mortgage",
      cash: "Cash / own funds",
      submit: "See matches",
    },
    citySpotlight: {
      label: "City spotlight",
      title: "Explore {city}",
      description: "Start with city-specific districts, live listing volume and the strongest new-build promotions.",
      liveListings: "Live listings",
      medianPrice: "Median price",
      newBuilds: "New builds",
      districtsEyebrow: "Districts",
      districtsTitle: "Start from a neighborhood",
      exploreDistrict: "Open district feed",
      promotionsEyebrow: "Launch offers",
      promotionsTitle: "Developer promotions in this city",
    },
    newBuild: {
      label: "New-build hub",
      title: "Developer launches and promoted inventory",
      description: "A dedicated surface for launch pricing, verified developers and mortgage-ready new-build stock.",
      partnerEyebrow: "Partner mortgages",
      partnerTitle: "Rates to compare alongside launch inventory",
    },
    listPage: {
      shareShortlist: "Share shortlist",
      sharedShortlistReady: "Shortlist link copied to clipboard.",
      shareUnavailable: "Sharing is unavailable in this browser.",
      compareNotesLabel: "Personal note",
      compareNotesPlaceholder: "What stands out here? commute, fit, renovation, next questions...",
    },
    single: {
      factDistrict: "District",
      factBuilding: "Building",
      factFinish: "Finish",
      factCondition: "Condition",
      factOwnership: "Ownership",
      factDeveloper: "Developer",
      factTransit: "Transit",
      condition: {
        managed: "Managed rental",
        launch: "Launch inventory",
        resale: "Resale",
      },
      ownership: {
        owner: "Verified owner",
        realtor: "Verified realtor",
        developer: "Verified developer",
      },
      historyLaunch: "Launch",
      history30d: "30 days",
      history14d: "14 days",
      historyNow: "Now",
      neighborhoodTitle: "Neighborhood insights",
      neighborhoodSchools: "Schools",
      neighborhoodTransit: "Transit",
      neighborhoodParks: "Parks",
      neighborhoodClinics: "Clinics",
      neighborhoodDining: "Dining",
      neighborhoodCommute: "Commute",
      minutes: "{value} min",
      priceHistoryTitle: "Price history and valuation",
      valuationRange: "Estimated market range",
      mortgageTitle: "Mortgage and affordability",
      mortgageRentHint: "Mortgage tools are focused on for-sale inventory. Use this section as a reference when you compare rent vs buy.",
      affordabilityTitle: "Comfort budget",
      affordabilityInput: "Target monthly budget",
      trustTitle: "Trust and verification",
      verifyPhotos: "All required photo categories are present",
      verifyOwnership: "Ownership / publisher identity checked",
      verifyModeration: "Listing passed moderation review",
      verifyDocuments: "Supporting documents or launch pack reviewed",
      antiFraudNote: "Always keep payments inside the official deal flow, confirm the viewing contact inside RomanEstate and never send a deposit before the scheduled visit is verified.",
      scheduleViewingTitle: "Schedule a viewing",
      viewingDate: "Preferred date",
      viewingTime: "Preferred time",
      viewingParty: "Party size",
      viewingMessage: "Add access notes, financing context or a preferred callback window.",
      viewingSuccess: "Viewing request saved. You can track it from your profile deals tab.",
      openProfileDeals: "Open profile deals",
      share: "Share",
      shareCopied: "Listing link copied to clipboard.",
      shareUnavailable: "Sharing is unavailable right now.",
      contactButton: "Call owner",
      mediaLabel: "Premium media",
      mediaTitle: "Video and 3D-tour readiness",
      mediaVideo: "Video walkthrough",
      media3d: "3D / immersive tour",
      mediaReady: "Ready for premium inventory",
      mediaPlaceholder: "Placeholder enabled for launch / premium flow",
      newBuild: "New build",
      priceReduced: "Price reduced",
      priceReducedBy: "Down by {amount} from launch",
      scheduleViewing: "Schedule viewing",
    },
    profile: {
      viewingsCount: "Viewing requests",
      viewingsEyebrow: "Viewing planner",
      viewingsTitle: "Scheduled or requested visits",
      viewingPending: "Time pending",
      viewingNoMessage: "No extra note added.",
      viewingEmptyTitle: "No viewing requests yet",
      viewingEmptyDescription: "Schedule a visit from any listing detail page and it will appear here.",
    },
  },
  ru: {
    nav: {
      newBuilds: "Новостройки",
    },
    home: {
      newBuildHub: "Перейти в хаб новостроек",
      digestEyebrow: "Дайджест поисков",
      digestTitle: "Быстрый обзор сохранённых поисков",
      digestMatches: "Активных совпадений: {count}",
      digestEmptyTitle: "Сохраните первый поиск",
      digestEmptyDescription: "Как только вы сохраните фильтры, здесь появится быстрый дайджест по ним.",
      recommendationEyebrow: "Рекомендуем дальше",
      recommendationTitle: "Объекты, к которым стоит вернуться",
      financeEyebrow: "Финансовые партнёры",
      financeTitle: "Ипотечные программы для раннего сравнения",
    },
    footer: {
      description:
        "Цифровой маркетплейс для поиска недвижимости, заявок на сделки и прямой связи с риелтором. Быстрый поиск, чистый сценарий сделки и безопасная ролевая логика.",
    },
    support: {
      loadError: "Не удалось загрузить чат.",
      sendError: "Не удалось отправить сообщение.",
      openAria: "Открыть чат поддержки",
      closeAria: "Закрыть чат поддержки",
    },
    filter: {
      reset: "Сбросить",
      advancedTitle: "Расширенный поиск",
      advancedDescription: "Добавьте район, транспорт, тип здания, отделку и сигналы по цене поверх базовых фильтров.",
      district: "Район",
      transit: "Транспорт",
      buildingType: "Тип здания",
      renovation: "Отделка",
      newBuild: "Новостройка",
      newBuildOnly: "Только новостройки",
      priceSignal: "Сигнал по цене",
      priceSignalDrop: "Цена снижена",
    },
    map: {
      searchAreaTitle: "Поиск по карте",
      searchAreaHint: "Нарисуйте зону, задайте радиус и сфокусируйте выдачу на нужной части города.",
      drawArea: "Нарисовать зону",
      drawingOn: "Рисование включено",
      radiusValue: "{value} км",
      searchThisArea: "Искать в этой зоне",
      resetArea: "Сбросить зону",
      activeAreaNotice: "Фильтр по карте активен: радиус {value} км.",
    },
    assistant: {
      label: "Поиск-помощник",
      title: "Опишите запрос обычным языком",
      description: "Опишите задачу свободно, а помощник аккуратно соберёт фильтры без обращения к живой LLM во время работы интерфейса.",
      placeholder: "Например: новостройка у метро в Мумбаи до 15000000",
      submit: "Построить поиск",
      exampleFamily: "Семейная квартира с 3 спальнями в Пуне до 18000000",
      exampleMetro: "Квартира у метро в Дели в аренду",
      exampleNewBuild: "Новостройка-кондо в Мумбаи со снижением цены",
    },
    quiz: {
      launch: "Пройти квиз",
      label: "Стартовый квиз",
      title: "Подскажите параметры поиска",
      description: "Короткий сценарий, который помогает быстрее собрать нужный набор фильтров.",
      close: "Закрыть",
      city: "Город",
      cityPlaceholder: "Mumbai",
      budget: "Бюджет",
      type: "Цель",
      property: "Тип объекта",
      finance: "Финансирование",
      mortgage: "Ипотека",
      cash: "Наличные / свои средства",
      submit: "Показать варианты",
    },
    citySpotlight: {
      label: "Фокус на городе",
      title: "Исследуйте {city}",
      description: "Начните с районов города, объёма живых объявлений и сильных промо по новостройкам.",
      liveListings: "Активные объекты",
      medianPrice: "Медианная цена",
      newBuilds: "Новостройки",
      districtsEyebrow: "Районы",
      districtsTitle: "Начните с района",
      exploreDistrict: "Открыть выдачу по району",
      promotionsEyebrow: "Стартовые предложения",
      promotionsTitle: "Промо от девелоперов в этом городе",
    },
    newBuild: {
      label: "Хаб новостроек",
      title: "Девелоперские запуски и промо-выкладка",
      description: "Отдельная поверхность для стартовых цен, проверенных девелоперов и новостроек с ипотечной готовностью.",
      partnerEyebrow: "Ипотечные партнёры",
      partnerTitle: "Ставки, которые удобно сравнить рядом с новостройками",
    },
    listPage: {
      shortlistCount: "В шортлисте",
      compareTitle: "Сравнение шортлиста",
      shareShortlist: "Поделиться шортлистом",
      sharedShortlistReady: "Ссылка на шортлист скопирована.",
      shareUnavailable: "В этом браузере нельзя поделиться ссылкой автоматически.",
      compareNotesLabel: "Личная заметка",
      compareNotesPlaceholder: "Что здесь важно: дорога, состояние, отделка, вопросы на показ...",
    },
    single: {
      factDistrict: "Район",
      factBuilding: "Тип здания",
      factFinish: "Отделка",
      factCondition: "Состояние",
      factOwnership: "Кто размещает",
      factDeveloper: "Девелопер",
      factTransit: "Транспорт",
      condition: {
        managed: "Управляемая аренда",
        launch: "Старт продаж",
        resale: "Вторичный рынок",
      },
      ownership: {
        owner: "Проверенный собственник",
        realtor: "Проверенный риелтор",
        developer: "Проверенный девелопер",
      },
      historyLaunch: "Старт",
      history30d: "30 дней",
      history14d: "14 дней",
      historyNow: "Сейчас",
      neighborhoodTitle: "Инфраструктура рядом",
      neighborhoodSchools: "Школы",
      neighborhoodTransit: "Транспорт",
      neighborhoodParks: "Парки",
      neighborhoodClinics: "Клиники",
      neighborhoodDining: "Кафе и рестораны",
      neighborhoodCommute: "Время в пути",
      minutes: "{value} мин",
      priceHistoryTitle: "История цены и оценка",
      valuationRange: "Оценочный рыночный диапазон",
      mortgageTitle: "Ипотека и бюджет",
      mortgageRentHint: "Ипотечные инструменты в первую очередь относятся к покупке. Для аренды используйте этот блок как ориентир при сравнении сценариев.",
      affordabilityTitle: "Комфортный бюджет",
      affordabilityInput: "Целевой платёж в месяц",
      trustTitle: "Доверие и проверка",
      verifyPhotos: "Все обязательные категории фото заполнены",
      verifyOwnership: "Проверена личность владельца / публикации",
      verifyModeration: "Объявление прошло модерацию",
      verifyDocuments: "Проверен пакет документов или материалов запуска",
      antiFraudNote: "Проводите платежи только внутри официального сценария сделки, подтверждайте контакт на показ внутри RomanEstate и не переводите задаток до подтверждённого визита.",
      scheduleViewingTitle: "Запланировать показ",
      viewingDate: "Предпочтительная дата",
      viewingTime: "Предпочтительное время",
      viewingParty: "Количество гостей",
      viewingMessage: "Добавьте комментарий: доступ, ипотека, удобное окно для звонка и другие детали.",
      viewingSuccess: "Запрос на показ сохранён. Отследить его можно в разделе сделок профиля.",
      openProfileDeals: "Открыть сделки в профиле",
      share: "Поделиться",
      shareCopied: "Ссылка на объект скопирована.",
      shareUnavailable: "Сейчас нельзя автоматически поделиться ссылкой.",
      contactButton: "Позвонить владельцу",
      mediaLabel: "Премиум-медиа",
      mediaTitle: "Готовность видео и 3D-тура",
      mediaVideo: "Видео-обзор",
      media3d: "3D-тур",
      mediaReady: "Готово для премиум-подачи",
      mediaPlaceholder: "Плейсхолдер включён для премиум-сценария и новостроек",
      newBuild: "Новостройка",
      priceReduced: "Цена снижена",
      priceReducedBy: "Ниже стартовой на {amount}",
      scheduleViewing: "Запланировать показ",
    },
    profile: {
      emptySavedDescription: "Сохраняйте понравившиеся объекты и собирайте свой шортлист здесь.",
      viewingsCount: "Показы",
      viewingsEyebrow: "Планировщик показов",
      viewingsTitle: "Запрошенные и назначенные визиты",
      viewingPending: "Время уточняется",
      viewingNoMessage: "Комментарий не добавлен.",
      viewingEmptyTitle: "Показов пока нет",
      viewingEmptyDescription: "Запланируйте визит с карточки объекта, и он появится здесь.",
    },
  },
};

const translations = mergeDictionaries(baseTranslations, translationExtensions);
function resolveKey(dictionary, key) {
  return key.split(".").reduce((current, part) => current?.[part], dictionary);
}

function interpolate(template, params) {
  if (typeof template !== "string") {
    return template;
  }

  return template.replace(/\{(\w+)\}/g, (_, token) => {
    return params[token] ?? `{${token}}`;
  });
}

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const stored = window.localStorage.getItem(STORAGE_KEY);
    return stored === "ru" ? "ru" : "en";
  });

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language === "ru" ? "ru" : "en";
  }, [language]);

  const t = (key, params = {}) => {
    const activeValue = resolveKey(translations[language], key);
    const fallbackValue = resolveKey(translations.en, key);
    return interpolate(activeValue ?? fallbackValue ?? key, params);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }

  return context;
}

